# Generated by Django 5.2.4 on 2025-07-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopApp',
            new_name='Product',
        ),
    ]
